#9 rozwiązanie zadania 4
mariaandrejczuk/java-wprowadzenie-tablice pull request #10
Opened 2020-12-11 14:12 UTC by mariaandrejczuk

2020-12-13 20:49 UTC, szymonleyk requested changes

2020-12-13 20:49 UTC, szymonleyk commented on Oceny2.java
> +        grades[4] = 1;
punkt 1 ok.

2020-12-13 20:49 UTC, szymonleyk commented on Oceny2.java
> +        System.out.print(" "+"\n");
wyświetlenie też ok.

2020-12-13 20:49 UTC, szymonleyk commented on Oceny2.java
> +        System.out.print(" "+"\n");
tutaj jest źle. Druga ocena miała zostać poprawiona na ocenę 5.

2020-12-13 20:49 UTC, szymonleyk commented on Oceny2.java
> +        System.out.println("Oceny od najmniejszej do największej: ");
tutaj źle. W tablicy elementy powinny być posortowane.

2020-12-14 13:28 UTC, mariaandrejczuk commented on Oceny2.java
> +        System.out.print(" "+"\n");
no tak, powinno być:
grades[1] = 5;
(a ja się odniosłam do poprzedniego podpunktu zadania).

2020-12-16 11:02 UTC, szymonleyk approved these changes

2020-12-16 11:10 UTC, merged